### ISSUE TITLE
Display configured role & region as part of `cca list`

### ISSUE THREAD

**Issue by ianhowell1** [ConnectedHomes/chaim#14]
It would be rather jolly nice if we could have some extra info as part of the `cca list` command, specifically the region set and the role, which may help in diagnosing user's issues.

**Comment by ccdale** [comment]
In progress - branch 'issue14'

**Comment by ccdale** [comment]
now gives the following output for `cca list`
```
 $ cca list
User Token Expires in 5 days at 08:29:58.
sadmin (apu/eu-west-1) Expires in 8 hours at 16:39:38. [96%] (DEFAULT)
sdev (apu/eu-west-1) Expires in 7 hours at 15:43:26. [85%] 
```
v2.5.0 of cca

**Comment by ccdale** [comment]
https://github.com/ConnectedHomes/chaim/pull/16 closes this issue
